# Generated by Django 4.2.7 on 2026-06-08 00:19

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', '管理员'), ('field_staff', '现场人员'), ('observer', '观察员')], default='observer', max_length=20, verbose_name='角色')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='手机号')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='器械名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='器械编号')),
                ('category', models.CharField(choices=[('cardio', '有氧'), ('strength', '力量'), ('flexibility', '柔韧'), ('other', '其他')], default='other', max_length=20, verbose_name='分类')),
                ('location', models.CharField(blank=True, default='', max_length=200, verbose_name='存放位置')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='购入日期')),
                ('status', models.CharField(choices=[('normal', '正常'), ('under_repair', '维修中'), ('retired', '已退役')], default='normal', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments', to=settings.AUTH_USER_MODEL, verbose_name='责任人')),
            ],
            options={
                'verbose_name': '器械',
                'verbose_name_plural': '器械',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_days', models.PositiveIntegerField(verbose_name='保养周期(天)')),
                ('last_maintenance_date', models.DateField(blank=True, null=True, verbose_name='上次保养日期')),
                ('next_maintenance_date', models.DateField(verbose_name='下次保养日期')),
                ('description', models.TextField(blank=True, default='', verbose_name='保养说明')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_plans', to='equipment.equipment', verbose_name='器械')),
            ],
            options={
                'verbose_name': '保养计划',
                'verbose_name_plural': '保养计划',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateTimeField(auto_now_add=True, verbose_name='巡查时间')),
                ('status', models.CharField(choices=[('normal', '正常'), ('abnormal', '异常')], default='normal', max_length=20, verbose_name='巡查状态')),
                ('issue_description', models.TextField(blank=True, default='', verbose_name='问题描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_records', to='equipment.equipment', verbose_name='器械')),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_records', to=settings.AUTH_USER_MODEL, verbose_name='巡查人')),
            ],
            options={
                'verbose_name': '巡查记录',
                'verbose_name_plural': '巡查记录',
                'ordering': ['-inspection_date'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('cycle', '保养周期'), ('consecutive_anomaly', '连续异常'), ('timeout', '处理超时'), ('duplicate_repair', '重复报修')], max_length=30, verbose_name='提醒类型')),
                ('title', models.CharField(max_length=200, verbose_name='提醒标题')),
                ('description', models.TextField(blank=True, default='', verbose_name='提醒描述')),
                ('issue_key', models.CharField(db_index=True, max_length=255, verbose_name='问题标识(去重用)')),
                ('status', models.CharField(choices=[('open', '待处理'), ('processing', '处理中'), ('closed', '已关闭')], db_index=True, default='open', max_length=20, verbose_name='状态')),
                ('close_request_note', models.TextField(blank=True, default='', verbose_name='关闭申请说明')),
                ('close_requested_at', models.DateTimeField(blank=True, null=True, verbose_name='关闭申请时间')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认关闭时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_alerts', to=settings.AUTH_USER_MODEL, verbose_name='指派处理人')),
                ('close_requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='close_requested_alerts', to=settings.AUTH_USER_MODEL, verbose_name='关闭申请人')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_alerts', to=settings.AUTH_USER_MODEL, verbose_name='确认关闭人')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='equipment.equipment', verbose_name='器械')),
            ],
            options={
                'verbose_name': '提醒',
                'verbose_name_plural': '提醒',
                'ordering': ['-created_at'],
            },
        ),
    ]
