# Generated by Django 4.2.7 on 2026-06-08 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_repairorder_repairprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='inspection_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='equipment.inspectionrecord', verbose_name='关联巡查记录'),
        ),
        migrations.AddField(
            model_name='inspectionrecord',
            name='resolution_result',
            field=models.TextField(blank=True, default='', verbose_name='处理结果'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('cycle', '保养周期'), ('consecutive_anomaly', '连续异常'), ('timeout', '处理超时'), ('duplicate_repair', '重复报修'), ('inspection_abnormal', '巡查异常')], max_length=30, verbose_name='提醒类型'),
        ),
        migrations.AlterField(
            model_name='inspectionrecord',
            name='status',
            field=models.CharField(choices=[('normal', '正常'), ('abnormal', '异常'), ('resolved', '已处理')], default='normal', max_length=20, verbose_name='巡查状态'),
        ),
    ]
